name: Build
run-name: ${{ gitea.actor }} is building
on: [push]

jobs:
  Dependencies_NPM:
    runs-on: Docker
    container:
      image: node:16
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Restore Cached Dependencies
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules
          key: node_modules
      - name: Install Dependencies
        run: npm ci
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node_modules
