name: Build
run-name: ${{ gitea.actor }} is building
on: [push]

jobs:
  Dependencies_NPM:
    runs-on: Docker
    container:
      image: node:16
    steps:
		
      - name: Checkout Repository
        uses: actions/checkout@v3
		
      - name: Install Dependencies
        run: npm i
	  
	  - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules
		  
  Build_Node:
	runs-on: Docker
	container:
	  image: node:16
    steps:
		- name: Build
		- run: npm run build