name: Continues Integration
on: [push, workflow_dispatch]

jobs:
  dependencies:
    name: Install dependencies
    runs-on: Docker
    container:
      image: node:16
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Restore Cached Dependencies
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules
          key: node_modules
          restore-keys: node_modules
      - name: Install Dependencies
        run: npm ci
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node_modules
          restore-keys: node_modules
  Docker:
    name: Install dependencies
    runs-on: Docker
    container:
      image: ubuntu:latest
    steps:

      - uses: ztimson/actions/docker@develop
        with:
          image: 291st
        secrets:
          registry_user: ztimson
          registry_pass: ${{secrets.deploy_token}}
