name: Continues Integration
on: [push, workflow_dispatch]

jobs:
  dependencies:
    name: Install dependencies
    container: node:16
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Restore Cached Dependencies
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules
          key: node_modules
          restore-keys: node_modules
      - name: Install Dependencies
        run: npm ci
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node_modules
          restore-keys: node_modules
  Docker:
    name: Push docker image
    container: git.zakscode.com/ztimson/ubuntu-docker:latest
    steps:

      - uses: ztimson/actions/docker@develop
        with:
          image: ztimson/291st
          registry_user: ztimson
          registry_pass: ${{secrets.deploy_token}}
